name = "itsabuzar99portfolio"
main = "src/worker.js"
compatibility_date = "2025-06-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "f5c18424df1641afac62f9b6c5de0867"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "portfolio"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
